name: Close issues marked 'fixed-pending-release' upon a release.
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
        token:
            description: "Access token that can access and update issues."
            required: true
        label:
            description: "Label for bugs that should be closed upon a release"
            required: false
        message:
            description: "The message to be included in a comment on the issues to be closed."
            required: false
        isExternalRelease:
            description: "Boolean indicating whether the release is external to GitHub. If it is, no GitHub release will be found."
            required: false



jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked 'fixed-pending-release' upon a release.
        uses: gcampbell-msft/fixed-pending-release@0.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: ${{ inputs.label }}
          message: ${{ inputs.message }}
          isExternalRelease: ${{ inputs.isExternalRelease }}